//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncIMEStatus.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyncIMEStatus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   React to Both に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strBoth {
            get {
                return ResourceManager.GetString("strBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strDetect {
            get {
                return ResourceManager.GetString("strDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strDoNothing {
            get {
                return ResourceManager.GetString("strDoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IME Off に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strImeOff {
            get {
                return ResourceManager.GetString("strImeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ime Off (SendMessage) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strImeOffAndSend {
            get {
                return ResourceManager.GetString("strImeOffAndSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IME On に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strImeOn {
            get {
                return ResourceManager.GetString("strImeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ime On (SendMessage) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strImeOnAndSend {
            get {
                return ResourceManager.GetString("strImeOnAndSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   React to KeyDown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strKeyDown {
            get {
                return ResourceManager.GetString("strKeyDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   React to KeyUp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strKeyUp {
            get {
                return ResourceManager.GetString("strKeyUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strNone {
            get {
                return ResourceManager.GetString("strNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strOff {
            get {
                return ResourceManager.GetString("strOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   On に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strOn {
            get {
                return ResourceManager.GetString("strOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pass Through Both に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strThroughBoth {
            get {
                return ResourceManager.GetString("strThroughBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pass Through Key Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strThroughKeyDown {
            get {
                return ResourceManager.GetString("strThroughKeyDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pass Through Key Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strThroughKeyUp {
            get {
                return ResourceManager.GetString("strThroughKeyUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strToggle {
            get {
                return ResourceManager.GetString("strToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle (SendMessage) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strToggleAndSend {
            get {
                return ResourceManager.GetString("strToggleAndSend", resourceCulture);
            }
        }
    }
}
